name: Clone wycheproof
description: Clones the wycheproof repository

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v4.2.2
      with:
        repository: "google/wycheproof"
        path: "wycheproof"
        ref: "master"
